MODULE IntrType
IMPLICIT NONE

   INTEGER, PARAMETER :: sdk = SELECTED_REAL_KIND(13, 307)
   !INTEGER, PARAMETER :: sdk = KIND(8)  ! 8-byte REAL
   INTEGER, PARAMETER :: sik = KIND(4)  ! 4-byte INTEGER

END MODULE IntrType   